name: Container-name healthcheck for Staging

on:
  push:
    branches:
      - main

env:
    DEPLOY_ENV: "production|qa|staging"

jobs:
  HEALTH-CHECK:
    runs-on: ubuntu-latest
    steps: 
      - id: health-check
        name: Health check
        run: |
          curl --location --request POST '[[ deflows-public-trigger-url ]]' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "key-1": "value-1",
              "key-2": "value-2"
          }'
          if [[ "$?" -eq "0" ]]; then
              echo "Healthcheck Passed"
          else
              echo "Healthcheck Failed"
          fi
