# Standard Eng.YAML CICD template
name: Publish/Deploy/Provision [container-name] to/for [environment]

on:
  push:
    branches:   # Only one branch should be selected here, the one mapping to the envrionment this workflow deploys to
      - main 
      - develop
env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  DEPLOY_ENV: "production|qa|staging" # replace with actual value

concurrency: 
  group: eng-yaml
  cancel-in-progress: false

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - id: CHECKOUT
        name: Checkout container source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: SETUP
        name: Prepare build server 
        run: echo "pre-build" # replace with actual code
      - id: BUILD
        name: Build the container code
        run: echo "build" # replace with actual code
      - id: UNIT-TEST
        name: Run unit tests
        run: echo "test" # replace with actual code
      - id: ANALYSIS  # OPTIONAL
        name: Run code analysis
        run: echo "Run code analysis" # replace with actual code
      - id: PUBLISH # OPTIONAL
        name: Publish built artifacts
        uses: publish-devfactory-nexus@v1 # example action for Devfactory Nexus
        with:
          username: $NEXUS_USERNAME
          password: $NEXUS_PASSWORD
          repository: maven-releases
          coordinates: groupId=com.example artifactId=app version=1.0.0
          assets: extension=jar
          filename: ./target/app-1.0.0.jar
  HEALTH-CHECK:
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
    - id: health-check
      name: Check the deployed service
      run: echo "check deployed service" # replace with actual code